<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<OutputType>Exe</OutputType>
		<Configurations>Debug;Release;DebugLocal</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Internationalization\de" />
		<EmbeddedResource Include="Internationalization\en" />
		<EmbeddedResource Include="test\contentTypeMultipartFormData1.post" />
		<EmbeddedResource Include="test\contentTypeMultipartFormData2.post" />
		<EmbeddedResource Include="test\contentTypeMultipartFormData3.post" />
		<EmbeddedResource Include="test\contentTypeMultipartFormData4.post" />
		<EmbeddedResource Include="test\contentTypeMultipartFormData_Umlaut.post" />
		<EmbeddedResource Include="test\contentTypeTextPlain.post" />
		<EmbeddedResource Include="test\contentTypeTextPlain_Umlaut.post" />
		<EmbeddedResource Include="test\contentTypeXwwwFormUrlencoded.post" />
		<EmbeddedResource Include="test\contentTypeXwwwFormUrlencoded_umlaut.post" />
		<EmbeddedResource Include="test\general.get" />
		<EmbeddedResource Include="test\less.get" />
		<EmbeddedResource Include="test\massive.get" />
		<EmbeddedResource Include="test\param.get" />
		<EmbeddedResource Include="test\param_umlaut.get" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets/**/*.*">
			<LogicalName>$(MSBuildProjectName).Assets.%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
		<PackageReference Include="xunit.v3" Version="4.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WebExpress.WebCore\WebExpress.WebCore.csproj" />
	</ItemGroup>

</Project>
