<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<Title>WebExpress.WebCore</Title>
		<Version>2.0.0.0</Version>
		<AssemblyVersion>2.0.0.0</AssemblyVersion>
		<TargetFramework>net10.0</TargetFramework>
		<RuntimeIdentifiers>any</RuntimeIdentifiers>
		<RepositoryUrl>https://github.com/webexpress-framework/WebExpress.git</RepositoryUrl>
		<Authors>webexpress-framework@outlook.com</Authors>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Company>webexpress-framework@outlook.com</Company>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>Core library of the WebExpress web server.</Description>
		<PackageVersion>2.0.0-alpha</PackageVersion>
		<PackageProjectUrl>https://github.com/webexpress-framework/WebExpress</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
		<PackageTags>webexpress</PackageTags>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<IsPackable>true</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Configurations>Debug;Release;DebugLocal</Configurations>
		<DisableImplicitStaticWebAssets>true</DisableImplicitStaticWebAssets>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.23.0" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.23.0" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Internationalization\de" />
		<EmbeddedResource Include="Internationalization\en" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\icon.png">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="ufo.ico">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="WebPermissions\" />
	</ItemGroup>

</Project>
